"""
Common JSON Normalizer for NEXUS-X

Provides standardized JSON schemas and normalization functions for all extracted data.
This ensures consistency across the entire extraction pipeline.

All extracted entities, relationships, events, and evidence should conform to these schemas.
"""

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field
import hashlib

logger = logging.getLogger(__name__)


class Provenance(BaseModel):
    """Provenance information tracking the source of extracted data."""
    document_id: str = Field(..., description="Unique identifier of the source document")
    source_file: str = Field(..., description="Original filename of the source document")
    source_type: str = Field(..., description="Type of source file (csv, json, txt, pdf)")
    row: Optional[int] = Field(None, description="Row number in the source document")
    page: Optional[int] = Field(None, description="Page number for PDF documents")
    line: Optional[int] = Field(None, description="Line number for text documents")
    field: Optional[str] = Field(None, description="Field/column name from the source")
    extracted_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat() + "Z", 
                           description="Timestamp when data was extracted")
    extraction_method: str = Field(default="llm", description="Method used for extraction (llm/deterministic)")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score of extraction")


class NormalizedEntity(BaseModel):
    """
    Standardized entity representation.
    
    All entities extracted from any source should be normalized to this format.
    """
    id: str = Field(..., description="Unique resolved entity ID (generated by entity_resolution)")
    entity_type: str = Field(..., description="Type of entity (PERSON, PHONE, VEHICLE, ACCOUNT, LOCATION, ORGANIZATION, EVENT, etc.)")
    original_value: str = Field(..., description="Original value as it appeared in the source")
    normalized_value: str = Field(..., description="Normalized value for comparison and lookup")
    display_name: Optional[str] = Field(None, description="Human-readable display name")
    attributes: Dict[str, Any] = Field(default_factory=dict, description="Additional attributes")
    provenance: Provenance = Field(..., description="Source provenance information")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Extraction confidence score")
    status: str = Field(default="EXTRACTED", description="Entity status (EXTRACTED, RESOLVED, VERIFIED, CONTRADICTED)")
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")


class NormalizedRelationship(BaseModel):
    """
    Standardized relationship representation.
    
    All relationships extracted from any source should be normalized to this format.
    """
    id: str = Field(..., description="Unique relationship ID")
    source_id: str = Field(..., description="Resolved entity ID of the source node")
    source_type: str = Field(..., description="Type of the source entity")
    target_id: str = Field(..., description="Resolved entity ID of the target node")
    target_type: str = Field(..., description="Type of the target entity")
    relationship_type: str = Field(..., description="Type of relationship (CALLED, USED, LOCATED_AT, etc.)")
    original_source_value: Optional[str] = Field(None, description="Original source value from document")
    original_target_value: Optional[str] = Field(None, description="Original target value from document")
    timestamp: Optional[str] = Field(None, description="Timestamp of the relationship/event")
    normalized_timestamp: Optional[str] = Field(None, description="ISO 8601 normalized timestamp")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Relationship confidence score")
    status: str = Field(default="POTENTIAL LEAD", description="Relationship status")
    attributes: Dict[str, Any] = Field(default_factory=dict, description="Additional relationship attributes")
    provenance: Provenance = Field(..., description="Source provenance information")
    evidence_id: Optional[str] = Field(None, description="Reference to supporting evidence")


class NormalizedEvent(BaseModel):
    """
    Standardized event representation.
    
    All temporal events should be normalized to this format.
    """
    id: str = Field(..., description="Unique event ID")
    event_type: str = Field(..., description="Type of event (CALL, TRANSACTION, MEETING, etc.)")
    timestamp: str = Field(..., description="Event timestamp")
    normalized_timestamp: str = Field(..., description="ISO 8601 normalized timestamp")
    description: Optional[str] = Field(None, description="Human-readable event description")
    participants: List[str] = Field(default_factory=list, description="List of resolved entity IDs involved")
    location_id: Optional[str] = Field(None, description="Resolved location entity ID")
    attributes: Dict[str, Any] = Field(default_factory=dict, description="Additional event attributes")
    provenance: Provenance = Field(..., description="Source provenance information")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Event confidence score")
    status: str = Field(default="EXTRACTED", description="Event status")


class NormalizedEvidence(BaseModel):
    """
    Standardized evidence representation.
    """
    id: str = Field(..., description="Unique evidence ID")
    hash: str = Field(..., description="SHA-256 hash of evidence content")
    content: Dict[str, Any] = Field(..., description="Evidence content as JSON")
    source: str = Field(..., description="Source of the evidence")
    entity_ids: List[str] = Field(default_factory=list, description="List of resolved entity IDs referenced")
    relationship_ids: List[str] = Field(default_factory=list, description="List of relationship IDs referenced")
    timestamp: str = Field(..., description="Evidence timestamp")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Evidence confidence score")
    processing_version: str = Field(..., description="Version of processing pipeline")
    provenance: Provenance = Field(..., description="Source provenance information")


class CommonJSONSchemas:
    """Container for all JSON schemas and validation."""
    
    ENTITY_SCHEMA = {
        "type": "object",
        "required": ["id", "entity_type", "original_value", "normalized_value", "provenance"],
        "properties": {
            "id": {"type": "string"},
            "entity_type": {"type": "string", "enum": [
                "PERSON", "PHONE", "EMAIL", "VEHICLE", "NUMBER_PLATE", "LOCATION", 
                "ORGANIZATION", "EVENT", "ACCOUNT", "DEVICE", "TRANSACTION", 
                "IP_ADDRESS", "DOMAIN", "URL", "DATE", "TIME", "DATETIME"
            ]},
            "original_value": {"type": "string"},
            "normalized_value": {"type": "string"},
            "display_name": {"type": "string"},
            "attributes": {"type": "object"},
            "provenance": {"type": "object"},
            "confidence": {"type": "number", "minimum": 0, "maximum": 1},
            "status": {"type": "string"},
            "created_at": {"type": "string", "format": "date-time"}
        }
    }
    
    RELATIONSHIP_SCHEMA = {
        "type": "object",
        "required": ["id", "source_id", "source_type", "target_id", "target_type", "relationship_type", "provenance"],
        "properties": {
            "id": {"type": "string"},
            "source_id": {"type": "string"},
            "source_type": {"type": "string"},
            "target_id": {"type": "string"},
            "target_type": {"type": "string"},
            "relationship_type": {"type": "string"},
            "original_source_value": {"type": "string"},
            "original_target_value": {"type": "string"},
            "timestamp": {"type": "string"},
            "normalized_timestamp": {"type": "string"},
            "confidence": {"type": "number", "minimum": 0, "maximum": 1},
            "status": {"type": "string"},
            "attributes": {"type": "object"},
            "provenance": {"type": "object"},
            "evidence_id": {"type": "string"}
        }
    }


def normalize_entity_data(raw_entity: Dict[str, Any], provenance_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Normalize raw entity data to the common JSON format.
    
    Args:
        raw_entity: Raw entity data from any extraction method
        provenance_data: Optional provenance information to merge
        
    Returns:
        Normalized entity dict conforming to NormalizedEntity schema
    """
    try:
        normalized = NormalizedEntity(**raw_entity)
        return normalized.dict()
    except Exception as e:
        logger.warning(f"[JSON_NORMALIZER] Entity normalization failed: {e}")
        # Fallback to basic normalization
        return _basic_entity_normalization(raw_entity, provenance_data)


def _basic_entity_normalization(raw_entity: Dict[str, Any], provenance_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Fallback normalization for entities that don't match the full schema."""
    entity_type = raw_entity.get("type", raw_entity.get("entity_type", "UNKNOWN")).upper()
    original_value = raw_entity.get("value", raw_entity.get("original_value", ""))
    normalized_value = raw_entity.get("normalized_value", original_value.lower() if isinstance(original_value, str) else str(original_value))
    
    # Create provenance if not provided
    if provenance_data:
        provenance = Provenance(**provenance_data).dict()
    else:
        provenance = {
            "document_id": raw_entity.get("document_id", "unknown"),
            "source_file": raw_entity.get("source_file", "unknown"),
            "source_type": raw_entity.get("source_type", "unknown"),
            "extraction_method": "deterministic",
            "confidence": raw_entity.get("confidence", 1.0)
        }
    
    return {
        "id": raw_entity.get("id", raw_entity.get("resolved_id", f"{entity_type}_{hashlib.md5(str(original_value).encode()).hexdigest()[:12]}")),
        "entity_type": entity_type,
        "original_value": original_value,
        "normalized_value": normalized_value,
        "display_name": original_value,
        "attributes": raw_entity.get("attributes", {}),
        "provenance": provenance,
        "confidence": raw_entity.get("confidence", 1.0),
        "status": raw_entity.get("status", "EXTRACTED"),
        "created_at": datetime.utcnow().isoformat() + "Z"
    }


def normalize_relationship_data(raw_relationship: Dict[str, Any], provenance_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Normalize raw relationship data to the common JSON format.
    
    Args:
        raw_relationship: Raw relationship data from any extraction method
        provenance_data: Optional provenance information to merge
        
    Returns:
        Normalized relationship dict conforming to NormalizedRelationship schema
    """
    try:
        normalized = NormalizedRelationship(**raw_relationship)
        return normalized.dict()
    except Exception as e:
        logger.warning(f"[JSON_NORMALIZER] Relationship normalization failed: {e}")
        return _basic_relationship_normalization(raw_relationship, provenance_data)


def _basic_relationship_normalization(raw_relationship: Dict[str, Any], provenance_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Fallback normalization for relationships."""
    # Handle different relationship formats from the workflow
    source_type = raw_relationship.get("source_type", "UNKNOWN").upper()
    source_val = raw_relationship.get("source_val", raw_relationship.get("source", ""))
    target_type = raw_relationship.get("target_type", "UNKNOWN").upper()
    target_val = raw_relationship.get("target_val", raw_relationship.get("target", ""))
    
    # Create provenance
    if provenance_data:
        provenance = Provenance(**provenance_data).dict()
    else:
        evidence = raw_relationship.get("evidence", {})
        provenance = {
            "document_id": evidence.get("document_id", "unknown") if isinstance(evidence, dict) else "unknown",
            "source_file": evidence.get("file", "unknown") if isinstance(evidence, dict) else "unknown",
            "source_type": evidence.get("source_type", "unknown") if isinstance(evidence, dict) else "unknown",
            "extraction_method": "deterministic",
            "confidence": raw_relationship.get("confidence", 1.0),
            "row": evidence.get("row") if isinstance(evidence, dict) else None
        }
    
    return {
        "id": raw_relationship.get("id", f"REL_{source_val}_{raw_relationship.get('relationship', 'UNKNOWN')}_{target_val}"),
        "source_id": source_val,
        "source_type": source_type,
        "target_id": target_val,
        "target_type": target_type,
        "relationship_type": raw_relationship.get("relationship", raw_relationship.get("type", "UNKNOWN")).upper(),
        "original_source_value": source_val,
        "original_target_value": target_val,
        "timestamp": raw_relationship.get("timestamp"),
        "confidence": raw_relationship.get("confidence", 1.0),
        "status": raw_relationship.get("status", "POTENTIAL LEAD"),
        "attributes": raw_relationship.get("attributes", {}),
        "provenance": provenance,
        "evidence_id": raw_relationship.get("evidence_id")
    }


def validate_entity(entity: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """
    Validate an entity against the common JSON schema.
    
    Args:
        entity: Entity dict to validate
        
    Returns:
        Tuple of (is_valid, list_of_errors)
    """
    errors = []
    
    required_fields = ["id", "entity_type", "original_value", "normalized_value"]
    for field in required_fields:
        if field not in entity or not entity[field]:
            errors.append(f"Missing required field: {field}")
    
    if "entity_type" in entity:
        valid_types = [
            "PERSON", "PHONE", "EMAIL", "VEHICLE", "NUMBER_PLATE", "LOCATION", 
            "ORGANIZATION", "EVENT", "ACCOUNT", "DEVICE", "TRANSACTION", 
            "IP_ADDRESS", "DOMAIN", "URL", "DATE", "TIME", "DATETIME"
        ]
        if entity["entity_type"].upper() not in valid_types:
            errors.append(f"Invalid entity_type: {entity['entity_type']}")
    
    if "confidence" in entity:
        if not isinstance(entity["confidence"], (int, float)) or not (0 <= entity["confidence"] <= 1):
            errors.append(f"Invalid confidence value: {entity['confidence']}")
    
    return len(errors) == 0, errors


def validate_relationship(relationship: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """
    Validate a relationship against the common JSON schema.
    
    Args:
        relationship: Relationship dict to validate
        
    Returns:
        Tuple of (is_valid, list_of_errors)
    """
    errors = []
    
    required_fields = ["id", "source_id", "source_type", "target_id", "target_type", "relationship_type"]
    for field in required_fields:
        if field not in relationship or not relationship[field]:
            errors.append(f"Missing required field: {field}")
    
    if "confidence" in relationship:
        if not isinstance(relationship["confidence"], (int, float)) or not (0 <= relationship["confidence"] <= 1):
            errors.append(f"Invalid confidence value: {relationship['confidence']}")
    
    return len(errors) == 0, errors


def batch_normalize_entities(raw_entities: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Normalize a batch of raw entities.
    
    Args:
        raw_entities: List of raw entity dicts
        
    Returns:
        List of normalized entity dicts
    """
    return [normalize_entity_data(entity) for entity in raw_entities]


def batch_normalize_relationships(raw_relationships: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Normalize a batch of raw relationships.
    
    Args:
        raw_relationships: List of raw relationship dicts
        
    Returns:
        List of normalized relationship dicts
    """
    return [normalize_relationship_data(rel) for rel in raw_relationships]


# Schema definitions for JSON schema validation
SCHEMAS = {
    "entity": CommonJSONSchemas.ENTITY_SCHEMA,
    "relationship": CommonJSONSchemas.RELATIONSHIP_SCHEMA
}


# Convenience functions
def get_entity_schema() -> Dict[str, Any]:
    """Get the entity JSON schema."""
    return SCHEMAS["entity"]


def get_relationship_schema() -> Dict[str, Any]:
    """Get the relationship JSON schema."""
    return SCHEMAS["relationship"]
